before_script:
  - TARGET='XVersion'

Building:
  stage: build
  tags:
    - version
  script:
    - xcodebuild build -workspace Example/${TARGET}.xcworkspace -scheme ${TARGET} -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11' ONLY_ACTIVE_ARCH=NO -quiet


Testing:
  stage: test
  tags:
    - version
  script:
    - pod install --project-directory=Example/
    - xcodebuild test -workspace Example/${TARGET}.xcworkspace -scheme ${TARGET}-Example -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11'  ONLY_ACTIVE_ARCH=NO

